version: "3"

services:
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: dockerfile.dev
    ports: 
      - 3000:${APP_PORT}
    volumes:
      - .:/app
    environment:
      PGPASSWORD: ${PG_PASSWORD}
      PGHOST: db
      PGUSER: ${PG_USER}
  db:
    image: postgres
    ports: 
      - 3001:5432
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}